services:
  nginx-proxy:
    build: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/tmp/default.conf
    environment: 
      - FLASK_SERVER_ADDR=flask-app:53424
    ports:
      - "53423:80"
    depends_on:
      - flask-app
    command: /app/start.sh
  flask-app:
    build: flask
    restart: always
    ports: 
      - '53424:53424'
    command: gunicorn -w 3 -t 60 -b 0.0.0.0:53424 app:app
  redis:
    image: redis
    volumes:
      - redis:/data
volumes:
  redis:
